# ── Fuzzel — Tokyo Night ───────────────────────────

[main]
font=CaskaydiaCove Nerd Font:size=11
dpi-aware=yes
prompt="❯ "
placeholder="Search apps…"
icon-theme=Tela-dark
icons-enabled=yes
terminal=kitty
lines=12
width=40
horizontal-pad=28
vertical-pad=12
inner-pad=4
line-height=24
match-mode=fzf
anchor=center
layer=overlay
use-bold=yes

[colors]
background=1a1b26ee
text=c0caf5ff
prompt=7aa2f7ff
placeholder=565f89ff
input=c0caf5ff
match=7dcfffff
selection=292e42ff
selection-text=c0caf5ff
selection-match=7dcfffff
border=3b4261ff

[border]
width=2
radius=14
selection-radius=8

[dmenu]
exit-immediately-if-empty=no
