# ── Fuzzel — Matcha Light（白天浅绿主题）────────────

[main]
font=CaskaydiaCove Nerd Font:size=11
dpi-aware=yes
prompt="❯ "
placeholder="Search apps…"
icon-theme=Tela-dark
icons-enabled=yes
terminal=kitty
lines=12
width=40
horizontal-pad=28
vertical-pad=12
inner-pad=4
line-height=24
match-mode=fzf
anchor=center
layer=overlay
use-bold=yes

[colors]
background=f2f6ecf2
text=3d4a44ff
prompt=4f9d57ff
placeholder=93a48fff
input=3d4a44ff
match=3fa98eff
selection=d7e5c6ff
selection-text=33413aff
selection-match=2e7d42ff
border=c2d3aeff

[border]
width=2
radius=14
selection-radius=8

[dmenu]
exit-immediately-if-empty=no
