# ── Mako — Matcha Light（白天浅绿主题）───────────────

font=CaskaydiaCove Nerd Font 11
width=360
height=120
padding=16
border-size=2
border-radius=12
anchor=top-right
layer=overlay
margin=48,10

background-color=#f2f6ecf2
text-color=#3d4a44
border-color=#4f9d57

progress-color=over #4f9d57

[urgency=high]
border-color=#d86666
